apiVersion: v1
data:
  config.yml: |-
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      headers:
        X-Content-Type-Options:
        - nosniff
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    version: 0.1
kind: ConfigMap
metadata:
  labels:
    app: docker-registry
    chart: docker-registry-1.14.0
    heritage: Helm
    release: docker-registry
  name: docker-registry-config
---
apiVersion: v1
data:
  haSharedSecret: bjRqUlJ2ZTd4VUVHSzZCWA==
  proxyPassword: ""
  proxyUsername: ""
kind: Secret
metadata:
  labels:
    app: docker-registry
    chart: docker-registry-1.14.0
    heritage: Helm
    release: docker-registry
  name: docker-registry-secret
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-registry
    chart: docker-registry-1.14.0
    heritage: Helm
    release: docker-registry
  name: docker-registry
spec:
  ports:
  - name: http-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: docker-registry
    release: docker-registry
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: docker-registry
    chart: docker-registry-1.14.0
    heritage: Helm
    release: docker-registry
  name: docker-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-registry
    chart: docker-registry-1.14.0
    heritage: Helm
    release: docker-registry
  name: docker-registry
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
      release: docker-registry
  template:
    metadata:
      annotations:
        checksum/config: 14a80a8250f8e431bea45db6590b1cd1de49727c5e668e4eb313e9786a959bb7
      labels:
        app: docker-registry
        release: docker-registry
    spec:
      containers:
      - command:
        - /bin/registry
        - serve
        - /etc/docker/registry/config.yml
        env:
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              key: haSharedSecret
              name: docker-registry-secret
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        image: registry:2.7.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 5000
        name: docker-registry
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/registry/
          name: data
        - mountPath: /etc/docker/registry
          name: docker-registry-config
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: docker-registry
      - configMap:
          name: docker-registry-config
        name: docker-registry-config
